import NAVIGATION from "@/common/constants/navigation";
import theme from "@/common/constants/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { DashboardLayout } from "@toolpad/core";
import { AppProvider } from "@toolpad/core/nextjs";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "@/styles/globals.css";
import { Box } from "@mui/material";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`} data-toolpad-color-scheme>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <AppProvider navigation={NAVIGATION} theme={theme}>
            <DashboardLayout>
              <Box
                sx={{
                  p: 4,
                  m: 4,
                  backgroundColor: "background.container",
                  borderRadius: "1rem",
                }}
              >
                {children}
              </Box>
            </DashboardLayout>
          </AppProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
